cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.jdk"
sudo: false
addons:
  apt:
    packages:
    - rpm
env:
  global:
  - TARGET="compile checkstyle findbugs test stage"
  - JDKW=https://raw.githubusercontent.com/vjkoskela/jdk-wrapper/master/jdk-wrapper.sh
  - secure: t1zhSaUKGmLRlnmfzQJYG2ZNfQoyJjQc1pgILOMMMsxFv3EEj0UILGtiC9vY0VJ3vJ3x4SMlkaaWQuxtCmv1/CjKNkBIIWYd5Oa5pcyuOFpawavhwuWOqD0Xn9mkaXzsB5hd46duWjFhpg67ZPiv60xf13pEiIc23u2SwB5wo8/BYBXWobbKDtPQKMIVIbgsU9eeQn//ewaWRpaM51z9qBwGLPuHNR714BJqSWvrI0TNAsrxKfGDm+eMIfkF/1tzFEYsQIbTydYniuvF8wFpJszXK+PYQxQtjO/GfIoAFlhkFA8eA+X13Qdk7TT4/nkKdm93MD5iTqzVF3INSDSSdXyTUOViMQK5vOihAKAAFS4pZdeBHFoCY00W3ABVGm+hnGRv9K7WbqAcWzUOvlFa7wIc5my+tXQrDmUVHfEHR4NCa/YHEnxgPPxU2rqlgn1PjY8X/m3Ex38VDJhFeNcSKaltD5wBGtPEOyfRdM6nGlcbPEMBd+3uCca9OMZbm5Jdh5GXMjeG8zDCrZ69AZBFHAbNe8+zhl4jk/7pKxpIA+6S8OFcwro4Dqd/nn5FTJ3G4LRUW41FH+Q+X5qV+c7+Jv9v+FL5CCcQjVNIMyAAmodnDf4slX+k6IpCDeDP95Ws4vuR08JjDxF20js02has7aS5T9IK/RIL/7T9+EogRyY=
  - secure: LjCTI432XX4Ir91gT8terShKhLg+myQlS9ziBCujKBc9cV/TVaXTnLLWJjKmsnbViAcn6FKvR0gXD6kYesHnfB5L6TQB9Gl1j+CCvk8/TaJA1pLth5VUu7c4zdYuHrbO09cTkY4G7o13/24zGoNlvzCMMHD3aJvwTNXuAf0YOjQNnvT30Xp5flKiig/E1qt6pZPBo71q1ysicS+NBhBSW08JFxLsQWuUyhSyTopVqDPDNzrg82zh+6ffS636h27YldjjgC3KWKeDiM+ZAisR0aWD/PGYddr6kCVuFXptr7GXg4MXfy5ucfwSJIpB5p3ZOhbzVg5u6OGJXNydW9i01aInMpTAdq7u3y/eHnepW/kBKNpP5HE4rbT9gd8Gc9EdV3G29/JBcR+GT4m9Vmr/08m0WtZc+DU8HY/IoYD8zdxTv8j0l4j/SmjLNpUu0FDWK1y+vnqBWbMkrxdKnl2b+PIf17ttuCnszFTjpGeDtPmRnEzAZ9QJFZLKcYoV45BGyJzScKn+YPkdZo7uZFgonBiylNXNBkVtb+TrJt+FGruECKv/oa6mNasRYEQGuyDjNKKzNFz8mFaLVNqaELVLlmysSQJd7ZeOaHaCR1JZx6PpSo8kycJbfY2iOt4KTJrnIP35EuO0AhWOcCjyuyE8zsTCexXm0ZtOI0SUZQBb0fA=
  - secure: VejlhzDTsc4aTZy+WmgWD0mmeJh2jbiFGeI302MpHQ6cfpOU+JKp13FWzr4v4YSs3L1bWZa7oc1EOLBtj4AQhIsauIHZQMLVp83NOcCfTl+S3JoMJ5vPgY79GFMqc9YvZsuuhq4T6RlCdQqUdxsKv8jm4mumxQh1HE5U1ulbAXNJQ+1GyfAJRSe/Ax2tcKk+80ealk4d8dwODba+0kkBzulsRkB76qrU/nLD1OCPFGxvdsT8sqzJqZoIRHLQUk2Yfsp2jpFaZ9bnEyPxsXt0zzw/FMfR7LpX2d3Fhb+xKqP5N53T9ElHbF3Q5tUeLlCSfyombhb9k21sBxwm1MrWmaBGmRyb07Zsc/AGO2FswVz3rbbHM1TMclVO27zuO/OdQSKpsPdE8NZvEdDUAMfxQ0Ooqjj8izwoh7JZzF6s4YazTJyRi0Dd34x4+20Om5PoUoRUlk0+TwFY57aQZ9M+cl5oaqUadGrzuiLNWNBs7kgRIT2/B0nVFxoZGBm/zV7+JrvyuZ2GzL5rH3gIfnyN12gwNW+VD6TCfiDnfoYkRApYCsBXqo/ZJrsNcy6UqulhAcI1O7RgYyyflq2jXFPGKXJYeQGNZKmP4TapQbIxFwrIVrfaUTjBBluOw+qH8mEXNArgBz3aZsPsZkWqUbQG5o+0wn3JAD3x2NEIf4+Tbz4=
install: true
before_script:
- gpg --import arpnetworking.key
- if [ \( -n "${TRAVIS_TAG}" \) -a  "${TRAVIS_PULL_REQUEST}" = "false" ]; then export
  TARGET="${TARGET} publishSigned sonatypeRelease rpm:packageBin universal:package-zip-tarball";
  fi;
script:
- curl -s ${JDKW} | bash /dev/stdin ./sbt clean ${TARGET}
deploy:
  provider: releases
  api_key:
    secure: rZgYpr8X4Bzc4XSam6mVwWtWEfcg8e1oOGILoxGDy9uWnZawK7HAO/g+E7nOGKhJCOsyeLN4X66HXGTAGlaT40T33rKW8pmsvcMNqLQaaBTH38+NyP8WBroVHI2qhRxtf1cdpwqREw5i+k5FoDCj2itEegbQHuHXAY+Eudax0xlFHL4PhsUP0/zkNQ2/JTCcbWcJO1SPQ1XpaIxq1iDlcre84oNu0TsUiU7jvOJLofxiFmM35BBUTgJxuJEMmrvol3/MxncPQlYUze1DViEmlvq5cBpJXGlLlrfKQ0KVYC0NcJO5EMkFfNjpCYrp/cVmOkOTfTHOImodRCrqNYYy2XX56UQ1QjA5EWCmkTidTI5FPC+2zUSgWWDlwuErmOPbBcZZZo/KDxFUR8AnUh4EDovzs0DcQ1hHADoq0+a74XkxT9KWr5vC2MNumsQwqLBCVqJ2GK5wEV+lU28C47vvNHzUdWcsR7M0F7k6BXGFXzK9Wmb/fo2kL/ed2rRbrGF1+fQVsTim1189Ara9wrP3Yyc0xx5hSn6FdeTXqOdPsP9LLP0Z3Rn2apsCgbnAd8HuxcM2L8K4LYvRYpKtZHjZ0cwaKxA/4eDk7GBRnCvLYX641Ma3iPSqCfkK530pEN1dapRnQDd6Y+qikXSWSs2qWKC4Qoud5XPYAo4HJJP6jp8=
  file:
  - target/rpm/RPMS/noarch/artemis*.rpm
  - target/universal/artemis*.tgz
  file_glob: true
  skip_cleanup: true
  on:
    repo: ArpNetworking/artemis
    tags: true
