sudo: false
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.jdk"
install: true
before_script:
- gpg --import groupon-api.key
script:
- curl -s ${JDKW} | bash /dev/stdin ./activator clean compile checkstyle findbugs test stage
- if [ \( -n "${TRAVIS_TAG}" \) -a  "${TRAVIS_PULL_REQUEST}" = "false" ]; then curl -s ${JDKW} | bash /dev/stdin ./activator publishSigned sonatypeRelease; fi;
env:
  global:
  - JDKW=https://raw.githubusercontent.com/vjkoskela/jdk-wrapper/master/jdk-wrapper.sh
  - JDKW_VERSION=8u65
  - JDKW_BUILD=b17
  - secure: tsVLcMZ4N2vw9myV99ytZWhuifI2T18VSOMeDy0/hJdRt3WBlyM4abv3eWCLzeVaHmaezA1YXXvkeh7ly99UrK4cFtjk7rkDLdk1XYkvTqMmSs1HeH1QtVgIKwk3eZzKV16AhuoZWvIj+qKFcxBr1ONjpKS0G0+Zx/OI356I0NEhm3PJiQjGiUdgIjREa9uyuZV+5caax5poqPJ4evEE0+g6WT+/UswOBd0IqlraPB/7aE1v4zpdqGdvAZxH+RsovQ6GHkFVX3T/bCL+R7bjdav4Emoh1cl4WcrleZw7r0CAhDWslwaLqeLkzgaz4KJDxSfQG7rbbFo4DrcCN7Ds/NiiwTqlVcMbkMWoRRvjKsEe3Xg8XAChnJCaXDJj4pEWKdSXaUesm87tLmvEn7ILz8lBcgm4bl6GxswHndwBk3ej+aDlMknJhwuvd+pRzWZO9S/W4D6/ATxSS5hnCxR2YzzWXZSEWJ6Xin15ElyfsW9QZv1TNhBYVjvX1TNuNUQDPZf4R/EEre/EQVWEvKVvDIGTdAS3qSvwEe4rN9AIxbXh3q89Bk3/8EVJSTtx2okWh9msIMwfvDIFW2dQ2KCYCNA8ZhBC+1qVsP7qQSBIoc+Z26hLzb/OZfBb7PSuK8NqiJtfZezCVGjk2VIxoKmOclZ/Hafh4BOS2am+m1w0O6c=
